Check PKCE/state in check session
ReachFive/identity-web-core-sdk pull request #127
Opened 2020-10-12 08:49 UTC by StanWarz

[[SDK core] Enforce PKCE code flow in checkSession](https://app.asana.com/0/982150578058310/1189474797301249/f)

2020-10-13 02:59 UTC, axuan25 requested changes
We can perhaps add some tests to ensure the new behavior

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
> +  pkceEnforced?: boolean
The value should always be present in theory. The `?` was probably used when the feature was first integrated.

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
> +    if (!this.config.sso && !opts.idTokenHint)
```suggestion
    if (this.config.sso)
```
The previous condition is no longer true. We cannot call loginFromSession and/or checkSession using ID Tokens.

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
> +    if (!this.config.sso && !opts.idTokenHint)
```suggestion
    if (this.config.sso)
```
Same as above. We need to remove this asap as it's been fixed at the backend a while ago.

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
>          new Error("Cannot call 'checkSession' without 'idTokenHint' parameter if SSO is not enabled.")
```suggestion
        new Error("Cannot call 'checkSession' if SSO is not enabled.")
```

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
>          new Error("Cannot call 'loginFromSession' without 'idTokenHint' parameter if SSO is not enabled.")
```suggestion
        new Error("Cannot call 'loginFromSession' if SSO is not enabled.")
```

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
> +    } else return computePkceParams()
1. Nitpick on terminology: I prefer sticking to "get" as we aren't building the PKCE params using any provided arguments
2. The error states implicit cannot be used when PKCE is enforced but does not check against the configuration

In this method, we need to check that:
```javascript
if (responseType === 'code') {
  computePkceParams()
} else {
  if (authParams.responseType === 'token' && this.config.pkceEnforced) {
    return Promise.reject(new Error('Cannot use implicit flow when PKCE is enforced'))
  } else {
    return Promise.resolve({})
  }
}
```
_(after which the returned promise will still be `Promise<PkceParams | {}>` whereas it is currently just `Promise<PkceParams>`)_

2020-10-13 02:59 UTC, axuan25 commented on src/main/apiClient.ts
> +      redirectUri: string,
```suggestion
    src: string,
    origin: string,
    redirectUri: string,
```

2020-10-13 09:33 UTC, axuan25 commented on CHANGELOG.md
> +Add the missing implementation of `Buffer` to address an issue with the UMD bundle when PKCE is enforced.
Back in early 2019, PKCE actually was either enabled or disabled. The change to "enforce" it came much later.

2020-10-13 09:33 UTC, axuan25 commented on src/main/apiClient.ts
> +    return Promise.resolve({})
Could we stick to complete expressions (if-else) instead of early returns?

2020-10-13 09:33 UTC, axuan25 commented on src/main/apiClient.ts
> +      computePkceParams()
```suggestion
      return computePkceParams()
```

2020-10-13 09:52 UTC, axuan25 reviewed
Last change suggestion:

Since passing a `redirect_uri` doesn't make much sense for our SDK users, we can remove the parameter altogether and hardcode `redirectUri` to `location.origin`.

2020-10-13 09:52 UTC, axuan25 commented on src/main/apiClient.ts
> +    redirectUri: string,
```suggestion
```

2020-10-13 09:52 UTC, axuan25 commented on src/main/apiClient.ts
> +              redirectUri,
```suggestion
              redirectUri: location.origin,
```

2020-10-13 09:52 UTC, axuan25 commented on src/main/apiClient.ts
> +        opts.redirectUri || "",
```suggestion
```

2020-10-13 09:52 UTC, axuan25 commented on src/main/apiClient.ts
> +          auth.redirectUri || "",
```suggestion
```

2020-10-14 06:42 UTC, axuan25 commented on CHANGELOG.md
> +Renamed pkceEnabled into pkceEnforced for the sake of comprehension.
```suggestion
Generate a PKCE code_challenge by default in all authorization code flows (`responseType === 'code'`)
Use the authorization code flow in checkSession

### Fixes
Renamed erroneously named config value `pkceEnabled` to `pkceEnforced`.
```

2020-10-14 10:16 UTC, axuan25 approved these changes
LGTM

2020-10-21 16:07 UTC, axuan25 approved these changes

2020-10-21 16:07 UTC, axuan25 commented on src/main/__tests__/remoteSettingsResolving.spec.ts
> +      pkceEnforced: false, // TODO STAN
👁️

2020-10-22 07:50 UTC, roxanemace approved these changes

2020-10-22 07:50 UTC, roxanemace commented on src/main/__tests__/remoteSettingsResolving.spec.ts
> +  expect(passwordLoginCall).toHaveBeenCalledWith(`https://${domain}/identity/v1/userinfo?fields=name`, {
👍

2020-10-22 07:50 UTC, roxanemace commented on src/main/__tests__/remoteSettingsResolving.spec.ts
> +      pkceEnforced: false, // TODO STAN
?

2020-10-22 08:01 UTC, StanWarz commented on src/main/__tests__/remoteSettingsResolving.spec.ts
> +  expect(passwordLoginCall).toHaveBeenCalledWith(`https://${domain}/identity/v1/userinfo?fields=name`, {
🙏

2020-10-23 04:29 UTC, axuan25 commented on src/main/apiClient.ts
> +    redirectUri ?: string,
```suggestion
    redirectUri?: string,
```

2020-10-30 10:00 UTC, merged