[CA-2152] Support du "discoverable login"
ReachFive/identity-web-core-sdk pull request #224
Opened 2024-01-30 19:58 UTC by FrancoisDevemy5

[As a Consumer, I want to signup & login using FIDO2 Passkeys on my web device](https://reach5.atlassian.net/browse/CA-2152)
Le discoverable login (c'est-à-dire la connexion avec clé sans avoir besoin de renseigner un identifiant) est supporté en deux mode : remplissage automatique (avec l'option `conditionalMediation` activée) et modal (ladite option désactivée).

NB : pour les modifs de formatage non liées au code que j'ai écrit, ce n'est pas de ma faute si les fichiers n'étaient pas déjà formatés correctement selon notre outil de formatage.
Donc pensez à activer l'option "hide whitespace".

2024-01-31 02:06 UTC, axuan25 approved these changes
👍

2024-01-31 14:49 UTC, moust requested changes

2024-01-31 14:49 UTC, moust commented on src/main/webAuthnClient.ts
> +    return (params as DiscoverableLoginWithWebAuthnParams).conditionalMediation !== undefined
Alors je sais que c'est courant de voir cette syntaxe dans notre code, mais c'est une mauvaise façon de faire car une variable "undefined" pourait très bien avoir été définie (ex: `var undefined = "oops"` et rendre ce test caduque.
La bonne manière de faire est d'utiliser le mot clé `typeof` :

```suggestion
    return typeof (params as DiscoverableLoginWithWebAuthnParams).conditionalMediation !== "undefined"
```

2024-01-31 14:49 UTC, moust commented on src/main/webAuthnClient.ts
> +    return queryParams.then((queryParams) => {
Un peu de refactoring et de typing au niveau de `queryParams`

```suggestion
    return this.buildWebAuthnParams(params).then((queryParams) => {
```

```typescript
// à checker au niveau de l'API si certaines propriétés comme `origin` ou `scope` par exemple ne sont pas optionels aussi
type LoginWithWebAuthnQueryParams = {
  body: {
    clientId: string
    origin: string
    scope: string
    email?: string
    phoneNumber?: string
  },
  conditionalMediationAvailable: boolean
}

private buildWebAuthnParams(params: LoginWithWebAuthnParams): Promise<LoginWithWebAuthnQueryParams> {
  if (this.isDiscoverable(params)) {
    const conditionalMediationAvailable =
      PublicKeyCredential.isConditionalMediationAvailable?.() ?? Promise.resolve(false)
    return conditionalMediationAvailable.then((conditionalMediationAvailable) => {
      if (params.conditionalMediation && !conditionalMediationAvailable) {
        return Promise.reject(new Error('Conditional mediation unavailable'))
      }
      return {
        body: {
          clientId: this.config.clientId,
          origin: window.location.origin,
          scope: resolveScope(params.auth, this.config.scope)
        },
        conditionalMediationAvailable: conditionalMediationAvailable
      }
    })
  } else {
    return Promise.resolve({
      body: {
        clientId: this.config.clientId,
        origin: window.location.origin,
        scope: resolveScope(params.auth, this.config.scope),
        email: (params as EmailLoginWithWebAuthnParams).email,
        phoneNumber: (params as PhoneNumberLoginWithWebAuthnParams).phoneNumber
      },
      conditionalMediationAvailable: false
    })
  } 
}
```

2024-02-06 13:05 UTC, moust requested changes

2024-02-06 22:57 UTC, FrancoisDevemy5 commented on src/main/webAuthnClient.ts
> +    PublicKeyCredential.isConditionalMediationAvailable?.() ?? Promise.resolve(false)
J'ai testé sur Firefox 110 et ça marche très bien.
ESLint doit être bourré.

2024-02-15 13:31 UTC, moust approved these changes

2024-02-28 13:55 UTC, merged